import type { QuizQuestion } from "@/types/quiz";

/**
 * CS3103-1: Theory of Computation — Unit I.
 * Source: N.M.A.M. Institute of Technology, Dept. of CSE, MCQ bank.
 *
 * Transcribed verbatim from the source PDF. A few notes on the source's
 * own answer key, worked out by re-deriving each answer independently:
 *
 *  - In the first block (toc-a1..toc-a13), question 2 ("5-tuple finite
 *    automata") is lettered A/B/C/D rather than a/b/c/d and its answer is
 *    given inline in the source as "Option D" rather than in the
 *    sequential answer list. The sequential list ("1. c, 2. a, 3. b, ...")
 *    therefore actually keys questions 1, 3, 4, 5, ... 13 in order (i.e.
 *    it skips over question 2, which is keyed separately). Reading it
 *    this way makes every single answer independently re-derivable from
 *    first principles (Kleene star vs. plus, string exponentiation,
 *    dead non-terminals, etc.) — reading it as a naive 1:1 sequential
 *    match to questions 1-13 does not. This file uses the re-derived
 *    reading.
 *  - toc-a13's grammar defines a production for "A" that "S" never
 *    produces (S only ever introduces "B"), so — taken literally — B can
 *    never be rewritten to a terminal string. The source lists no answer
 *    for this question; "Φ" (empty language) is the correct reading of
 *    the grammar exactly as printed, and is included as the answer here.
 *
 * Everything else matches the source answer key exactly on independent
 * re-derivation (spot-checked throughout Unit 1: Finite Automata).
 */
export const questions: QuizQuestion[] = [
  // ---- Section: UNIT I MCQs -------------------------------------------------
  {
    id: "toc-a1",
    text: "Which is correct?",
    topic: "Finite Automata",
    options: [
      { id: "a", text: "a^+ = a^*. a^*" },
      { id: "b", text: "a^* = a^+. a^+" },
      { id: "c", text: "a^+ = a^*. a" },
      { id: "d", text: "a^* = a^+. a^*" },
    ],
    correctOptionId: "c",
    explanation:
      "a+ means one or more repetitions of a, while a* allows zero or more. Since a+ requires at least one a, it can be built as a* (zero or more) followed by exactly one more a, so a+ = a*.a.",
  },
  {
    id: "toc-a2",
    text: "Which of the following is not a part of the 5-tuple definition of a finite automaton?",
    topic: "Finite Automata",
    options: [
      { id: "a", text: "Input alphabet" },
      { id: "b", text: "Transition function" },
      { id: "c", text: "Initial state" },
      { id: "d", text: "Output alphabet" },
    ],
    correctOptionId: "d",
    explanation:
      "A finite automaton is formally the 5-tuple (Q, Σ, δ, q0, F): a finite set of states, an input alphabet, a transition function, an initial state, and a set of final states. An 'output alphabet' belongs to output-producing machines like Mealy or Moore machines, not to a plain finite automaton.",
  },
  {
    id: "toc-a3",
    text: "(a, b)* means",
    topic: "Finite Automata",
    options: [
      { id: "a", text: "Any combination of a, b including null" },
      { id: "b", text: "Any combination of a, b excluding null" },
      { id: "c", text: "Any combination of a, b, but 'a' will come first" },
      { id: "d", text: "None of these" },
    ],
    correctOptionId: "a",
    explanation:
      "The Kleene star (*) denotes zero or more repetitions, so it always includes the empty (null) string as one possibility.",
  },
  {
    id: "toc-a4",
    text: "(a, b)+ means",
    topic: "Finite Automata",
    options: [
      { id: "a", text: "Any combination of a, b including null" },
      { id: "b", text: "Any combination of a, b excluding null" },
      { id: "c", text: "Any combination of a, b, but 'a' will come first" },
      { id: "d", text: "None of these" },
    ],
    correctOptionId: "b",
    explanation:
      "The Kleene plus (+) denotes one or more repetitions, so it requires at least one symbol and therefore excludes the null string — unlike *, which does include it.",
  },
  {
    id: "toc-a5",
    text: "What is the language generated by the grammar S → aSb, S → A, A → aA?",
    topic: "Finite Automata",
    options: [
      { id: "a", text: "a^m b^m" },
      { id: "b", text: "∅" },
      { id: "c", text: "a^n b^m" },
      { id: "d", text: "a^m b^m" },
    ],
    correctOptionId: "b",
    explanation:
      "Every derivation eventually reaches A, but A → aA is the only production for A — there is no rule that lets A produce a string of terminals only. So no derivation from S ever finishes as a string made only of terminals, and the language generated is empty (∅).",
  },
  {
    id: "toc-a6",
    text: "The language generated by the grammar S → 0S0, S → 1S1, S → 0, S → 1 is",
    topic: "Finite Automata",
    options: [
      { id: "a", text: "Even palindrome of 0 and 1" },
      { id: "b", text: "Odd palindrome of 0 and 1" },
      { id: "c", text: "Any combination of 0 and 1" },
      { id: "d", text: "None of these" },
    ],
    correctOptionId: "b",
    explanation:
      "Each recursive step wraps a matching symbol on both sides (0S0 or 1S1), and the base case (S → 0 or S → 1) contributes a single middle symbol. That always builds a palindrome of odd length, since the string grows outward from one central symbol.",
  },
  {
    id: "toc-a7",
    text: "Which of the following grammar generates strings with any number of 1's?",
    topic: "Finite Automata",
    options: [
      { id: "a", text: "S → 1A, A → ε" },
      { id: "b", text: "S → 1S, S → ε" },
      { id: "c", text: "S → S1, S → ε" },
      { id: "d", text: "(b) & (c)" },
    ],
    correctOptionId: "d",
    explanation:
      "S → 1A, A → ε can only ever produce the single string '1', since A cannot recurse. Both S → 1S | ε (left-recursive) and S → S1 | ε (right-recursive) can repeat their base case any number of times, so both correctly generate 1* = {ε, 1, 11, 111, ...} — making (b) & (c) the complete answer.",
  },
  {
    id: "toc-a8",
    text: "Which of the following is true?",
    topic: "Finite Automata",
    options: [
      { id: "a", text: "(ab)^2 = a^2b^2" },
      { id: "b", text: "(ab)^2 = abab" },
      { id: "c", text: "(ab)^2 = aabb" },
      { id: "d", text: "None of these" },
    ],
    correctOptionId: "b",
    explanation:
      "Exponentiation on strings means repeated concatenation, not distributing the exponent over each symbol like algebra. So (ab)^2 = (ab)(ab) = abab.",
  },
  {
    id: "toc-a9",
    text: "If ∑ = {1}, then ∑* – ∑+ is",
    topic: "Finite Automata",
    options: [
      { id: "a", text: "1^+" },
      { id: "b", text: "{1}" },
      { id: "c", text: "{ε}" },
      { id: "d", text: "{ε, 1, 11…..}" },
    ],
    correctOptionId: "c",
    explanation:
      "Σ* is the empty string plus everything in Σ+. Σ+ is exactly that same set without the empty string. Subtracting Σ+ from Σ* leaves only the empty string, {ε}.",
  },
  {
    id: "toc-a10",
    text: "A language set contains",
    topic: "Finite Automata",
    options: [
      { id: "a", text: "Alphabet" },
      { id: "b", text: "String" },
      { id: "c", text: "Set" },
      { id: "d", text: "None of these" },
    ],
    correctOptionId: "b",
    explanation:
      "A language is defined as a set of strings over some alphabet, so the elements of a language are strings.",
  },
  {
    id: "toc-a11",
    text: "In automata, why it is called formal language?",
    topic: "Finite Automata",
    options: [
      { id: "a", text: "Some alphabet forms a string" },
      { id: "b", text: "Some strings form a language" },
      { id: "c", text: "Well-defined use of symbols is significant" },
      { id: "d", text: "Only the form of the string generated by alphabets is significant." },
    ],
    correctOptionId: "d",
    explanation:
      "It's called 'formal' because only the syntactic form of the strings that can be generated from the alphabet matters here — meaning and interpretation are set aside entirely.",
  },
  {
    id: "toc-a12",
    text: "The language constructed from the grammar S → aSbb/aAbb, A →a is",
    topic: "Finite Automata",
    options: [
      { id: "a", text: "a^(n+1) b^(2n)" },
      { id: "b", text: "a^n b^(2n)" },
      { id: "c", text: "a^n b^(2n-1)" },
      { id: "d", text: "a^(n+1) b^(2n+1)" },
    ],
    correctOptionId: "a",
    explanation:
      "Applying S → aSbb k times gives a^k S b^(2k). Switching to S → aAbb once gives a^(k+1) A b^(2k+2), and A → a finishes it as a^(k+2) b^(2k+2). Writing n = k+1 (n ≥ 1), that's a^(n+1) b^(2n).",
  },
  {
    id: "toc-a13",
    text: "The language generated by the grammar S → aSa/aBa, A → Ba/b is",
    topic: "Finite Automata",
    options: [
      { id: "a", text: "a^n b a^n" },
      { id: "b", text: "a^n b a^(n+1)" },
      { id: "c", text: "a^2n" },
      { id: "d", text: "Φ" },
    ],
    correctOptionId: "d",
    explanation:
      "S only ever introduces the non-terminal B (via S → aBa), but the grammar's second rule defines productions for A, not B. With no rule that rewrites B into anything, no derivation can ever finish as a string of terminals only — so the language generated is empty (Φ).",
  },

  // ---- Section: UNIT-1: Finite Automata --------------------------------------
  {
    id: "toc-fa1",
    text: "A language L from a grammar G = {V_N, Σ, P, S} is",
    topic: "Finite Automata",
    options: [
      { id: "a", text: "Set of symbols over V_N" },
      { id: "b", text: "Set of symbols over Σ" },
      { id: "c", text: "Set of symbols over P" },
      { id: "d", text: "Set of symbols over S" },
    ],
    correctOptionId: "b",
    explanation:
      "The language generated by a grammar is a set of strings made entirely of terminal symbols — that is, symbols drawn from Σ, the terminal alphabet.",
  },
  {
    id: "toc-fa2",
    text: "Which is true for δ(q, ab)",
    topic: "Finite Automata",
    options: [
      { id: "a", text: "δ(q, a) ∪ δ(q, b)" },
      { id: "b", text: "δ(δ(q, a), b)" },
      { id: "c", text: "δ(q, a), b" },
      { id: "d", text: "δ(q, a) ∩ δ(q, b)" },
    ],
    correctOptionId: "b",
    explanation:
      "Reading a string one symbol at a time, the transition function is applied step by step: first move on 'a' to reach δ(q,a), then move on 'b' from that resulting state — giving δ(δ(q,a), b).",
  },
  {
    id: "toc-fa3",
    text: "The transitional function of a DFA is",
    topic: "Finite Automata",
    options: [
      { id: "a", text: "Q × Σ → Q" },
      { id: "b", text: "Q × Σ → 2^Q" },
      { id: "c", text: "Q × Σ → 2^n" },
      { id: "d", text: "Q × Σ → Q^n" },
    ],
    correctOptionId: "a",
    explanation: "A DFA is deterministic: each (state, symbol) pair maps to exactly one next state, δ: Q × Σ → Q.",
  },
  {
    id: "toc-fa4",
    text: "The transitional function of an NFA is",
    topic: "Finite Automata",
    options: [
      { id: "a", text: "Q × Σ → Q" },
      { id: "b", text: "Q × Σ → 2^Q" },
      { id: "c", text: "Q × Σ → 2^n" },
      { id: "d", text: "Q × Σ → Q^n" },
    ],
    correctOptionId: "b",
    explanation:
      "An NFA may move to any number of possible next states on a given symbol, so its transition function maps into the power set of Q: δ: Q × Σ → 2^Q.",
  },
  {
    id: "toc-fa5",
    text: "The maximum number of states of a DFA converted from an NFA with n states is",
    topic: "Finite Automata",
    options: [
      { id: "a", text: "n" },
      { id: "b", text: "n^2" },
      { id: "c", text: "2^n" },
      { id: "d", text: "None of these" },
    ],
    correctOptionId: "c",
    explanation:
      "The subset construction builds one DFA state for every possible subset of the NFA's n states, so the resulting DFA has at most 2^n states.",
  },
  {
    id: "toc-fa6",
    text: "A string after full traversal is called not accepted by an NFA if it results in",
    topic: "Finite Automata",
    options: [
      { id: "a", text: "Some non-final states" },
      { id: "b", text: "All non-final states" },
      { id: "c", text: "A single non-final state" },
      { id: "d", text: "Some final states" },
    ],
    correctOptionId: "b",
    explanation:
      "An NFA accepts a string if at least one of the possible resulting states after reading it is final. It only rejects the string when every reachable state after traversal is non-final.",
  },
  {
    id: "toc-fa7",
    text: "An NFA with a set of states Q is converted to an equivalent DFA with a set of states Q′. Find which is true.",
    topic: "Finite Automata",
    options: [
      { id: "a", text: "Q′ = Q" },
      { id: "b", text: "Q′ ⊆ Q" },
      { id: "c", text: "Q ⊆ Q′" },
      { id: "d", text: "None of these" },
    ],
    correctOptionId: "d",
    explanation:
      "Each DFA state built by the subset construction is actually a set of NFA states — so Q′ is built from the power set of Q, not simply equal to or a subset of Q itself.",
  },
  {
    id: "toc-fa8",
    text: "The basic limitations of a finite state machine is",
    topic: "Finite Automata",
    options: [
      { id: "a", text: "It cannot remember arbitrarily large amount of information" },
      { id: "b", text: "It cannot remember state transitions" },
      { id: "c", text: "It cannot remember grammar for a language" },
      { id: "d", text: "It cannot remember language generated from a grammar" },
    ],
    correctOptionId: "a",
    explanation:
      "An FSM has only a fixed, finite number of states and no auxiliary memory such as a stack or tape, so it cannot count or store an unbounded amount of information about what it has read.",
  },
  {
    id: "toc-fa9",
    text: "The string WW^R is not recognized by any FSM because",
    topic: "Finite Automata",
    options: [
      { id: "a", text: "An FSM cannot remember arbitrarily large amount of information" },
      { id: "b", text: "An FSM cannot fix the mid-point" },
      { id: "c", text: "An FSM cannot match W with W^R" },
      { id: "d", text: "An FSM cannot remember the first and last inputs." },
    ],
    correctOptionId: "b",
    explanation:
      "To confirm the second half mirrors the first half, the machine would need to know exactly where the string's midpoint falls. Since W can be arbitrarily long, a machine with only finitely many states can't mark or locate that midpoint.",
  },
  {
    id: "toc-fa10",
    text: "A finite automata recognizes",
    topic: "Finite Automata",
    options: [
      { id: "a", text: "Any language" },
      { id: "b", text: "Context sensitive language" },
      { id: "c", text: "Context-free language" },
      { id: "d", text: "Regular language" },
    ],
    correctOptionId: "d",
    explanation: "By definition, the class of languages recognized by finite automata is exactly the regular languages.",
  },
  {
    id: "toc-fa11",
    text: "Which is true for a dead state?",
    topic: "Finite Automata",
    options: [
      { id: "a", text: "It cannot be reached anytime" },
      { id: "b", text: "There is no necessity of the state" },
      { id: "c", text: "If control enters, there is no way to come out from the state" },
      { id: "d", text: "If control enters, FA is dead" },
    ],
    correctOptionId: "c",
    explanation:
      "A dead (trap) state is a non-final state that, once entered, has no path back to any final state — the automaton is stuck there for the rest of the input.",
  },
  {
    id: "toc-fa12",
    text: "The language accepted by the given FA is",
    topic: "Finite Automata",
    options: [
      { id: "a", text: "(ab)*" },
      { id: "b", text: "bb*a" },
      { id: "c", text: "b(ba)*a" },
      { id: "d", text: "Null" },
    ],
    correctOptionId: "d",
    explanation:
      "B is drawn as the only accepting state, but its single edge only goes out to A — nothing ever transitions into B from the start state A or from C. Since the accepting state can never be reached, this automaton accepts no string at all: the language is Null (∅).",
  },
  {
    id: "toc-fa13",
    text: "In the previous FA, B is called",
    topic: "Finite Automata",
    options: [
      { id: "a", text: "Dead state" },
      { id: "b", text: "Inaccessible state" },
      { id: "c", text: "Both a and b" },
      { id: "d", text: "None of these" },
    ],
    correctOptionId: "b",
    explanation:
      "B has no incoming transitions from the reachable part of the automaton, so it can never be entered at all — that makes it an inaccessible (unreachable) state, not a dead state (a dead state can be entered, just never left).",
  },
  {
    id: "toc-fa14",
    text: "Which is true for the inaccessible state?",
    topic: "Finite Automata",
    options: [
      { id: "a", text: "It cannot be reached anytime" },
      { id: "b", text: "There is no necessity of the state" },
      { id: "c", text: "If control enters, there is no way to come out from the state" },
      { id: "d", text: "If control enters, FA is dead" },
    ],
    correctOptionId: "a",
    explanation:
      "An inaccessible (unreachable) state has no path leading into it from the start state, so control can never reach it during any computation.",
  },
  {
    id: "toc-fa15",
    text: "Which type of string is accepted by the following finite automata?",
    topic: "Finite Automata",
    options: [
      { id: "a", text: "All string" },
      { id: "b", text: "Null string" },
      { id: "c", text: "No string" },
      { id: "d", text: "All of the above" },
    ],
    correctOptionId: "b",
    explanation:
      "The diagram shows a single state that is both the start state and the only accepting state, with no transitions leaving it. The automaton accepts by staying in that state without consuming any input at all — meaning it accepts exactly the empty (null) string, and nothing else.",
  },

  // ---- Section: GATE Questions (Unit 1 supplement) ---------------------------
  // Four questions from this source section are not included yet: two involve
  // hand-drawn multi-state diagrams (the "S0/S1/S3/S4" DFA and the 7-bit-string
  // DFA M) whose exact edge layout doesn't reconstruct reliably from the PDF's
  // extracted text, and two more (the "product automaton Z x Y" and "valid
  // minimal DFA" questions) have answer *options* that are themselves sets of
  // small diagrams/tables, which carries the same problem. Rather than guess,
  // they're left out until the source images can be reviewed directly. Every
  // question below was independently re-derived and checked against the
  // source's answer key before being included.
  {
    id: "toc-g1",
    text: "Consider the strings u = abbaba, v = bab, and w = aabb. Which of the following statement is true for the given transitional system?",
    topic: "Finite Automata — GATE Questions",
    options: [
      { id: "a", text: "The automaton accepts u and v but not w." },
      { id: "b", text: "The automaton accepts each of u, v, and w." },
      { id: "c", text: "The automaton rejects each of u, v, and w." },
      { id: "d", text: "The automaton accepts u but rejects v and w." },
    ],
    correctOptionId: "d",
    explanation:
      "Tracing each string from S: u = abbaba moves S→r→r→r→S→t→t, ending on the accepting state t, so u is accepted. v = bab moves S→t→t→S, ending on S (not accepting), so v is rejected. w = aabb moves S→r→S→t→S, also ending on S, so w is rejected too. Only u is accepted.",
  },
  {
    id: "toc-g2",
    text: "Consider the transitional system shown. Which of the states are to be marked as starting state and final state, respectively, so as to turn the above system into a DFA that accepts all strings having odd number of zeros and even number of 1's?",
    topic: "Finite Automata — GATE Questions",
    options: [
      { id: "a", text: "q0, q2" },
      { id: "b", text: "q0, q1" },
      { id: "c", text: "q1, q2" },
      { id: "d", text: "None of these" },
    ],
    correctOptionId: "c",
    explanation:
      "Label each state by (parity of 0's seen, parity of 1's seen) relative to wherever you start. Starting at q1 and following the transitions around to q2 takes exactly one net 0-edge and an even number of net 1-edges — i.e. an odd count of 0's and an even count of 1's. So start = q1, final = q2.",
  },
  {
    id: "toc-g4",
    text: "Let N be an NFA with n states and let M be the minimized DFA with m states recognizing the same language. Which of the following is NECESSARILY true?",
    topic: "Finite Automata — GATE Questions",
    options: [
      { id: "a", text: "m ≤ 2^n" },
      { id: "b", text: "n ≤ m" },
      { id: "c", text: "M has one accept state" },
      { id: "d", text: "m = 2^n" },
    ],
    correctOptionId: "a",
    explanation:
      "The subset construction always produces a DFA with at most 2^n states — one per subset of the NFA's n states — so m ≤ 2^n always holds. It need not equal 2^n exactly, the minimized DFA can end up with fewer or more states than n, and it can have any number of accept states.",
  },
  {
    id: "toc-g5",
    text: "If the final state and non-final states in the following DFA are interchanged, then which of the following languages over the alphabet (a, b) will be accepted by the new DFA?",
    topic: "Finite Automata — GATE Questions",
    options: [
      { id: "a", text: "Set of all strings that do not end with ab" },
      { id: "b", text: "Set of all strings that begin with either an a or a b." },
      { id: "c", text: "Set of all strings that do not contain the substring ab." },
      { id: "d", text: "The set described by the regular expression b*aa*(ba)*b*" },
    ],
    correctOptionId: "a",
    explanation:
      "The original DFA (with q2 as the single accepting state) recognizes exactly the strings that end in 'ab' — the standard 3-state construction shown. Swapping which states are accepting always turns a DFA's language into its complement, so the new DFA accepts everything that does NOT end in 'ab'.",
  },
  {
    id: "toc-g6",
    text: "A finite state machine with the following state table has a single input x and a single output z. If the initial state is unknown, then the shortest input sequence to reach the final state C is:",
    topic: "Finite Automata — GATE Questions",
    options: [
      { id: "a", text: "01" },
      { id: "b", text: "10" },
      { id: "c", text: "101" },
      { id: "d", text: "110" },
    ],
    correctOptionId: "b",
    explanation:
      "Since the start state is unknown, a sequence only works if it reaches C from every possible starting state. Checking '10' from A, B, C, and D each lands on C after two steps (e.g. from A: A→(1)→D→(0)→C), while '01' fails from A (it lands on B instead). No length-1 sequence works from every state either, so '10' is the shortest sequence guaranteed to work.",
  },
  {
    id: "toc-g7",
    text: "Which of the following sets can be recognized by a deterministic finite state automaton?",
    topic: "Finite Automata — GATE Questions",
    options: [
      { id: "a", text: "The numbers 1, 2, 4, 8, . . . 2^n written in binary." },
      { id: "b", text: "The numbers 1, 2, 4, . . . 2^n written in unary." },
      { id: "c", text: "The set of binary string in which the number of zeros is the same as the number of ones." },
      { id: "d", text: "The set {1, 101, 11011, 1110111, . . .}" },
    ],
    correctOptionId: "a",
    explanation:
      "Written in binary, every power of two is just '1' followed by some number of zeros — the language 1·0*, which is trivially regular. The unary encoding of 2^n requires counting up to an exponentially growing value, matching equal counts of 0's and 1's requires unbounded counting, and the 1^n·0·1^n pattern needs to match counts on both sides of the 0 — none of those can be done with a fixed number of states.",
  },
  {
    id: "toc-g8",
    text: "Consider the regular expression (0 + 1)(0 + 1) . . . . . N times. The minimum state FA that recognizes the language represented by this regular expression contains",
    topic: "Finite Automata — GATE Questions",
    options: [
      { id: "a", text: "n states" },
      { id: "b", text: "(n + 1) states" },
      { id: "c", text: "(n + 2) states" },
      { id: "d", text: "None of the above" },
    ],
    correctOptionId: "b",
    explanation:
      "This regular expression matches exactly N symbols from {0,1}. A counting chain with N+1 states — 'seen 0 symbols so far', 'seen 1', ..., up to 'seen N' (accepting) — recognizes it, since only the count of symbols read matters, not which ones.",
  },
  {
    id: "toc-g9",
    text: "What can be said about a regular language L over {a} whose minimal finite state automation has two states?",
    topic: "Finite Automata — GATE Questions",
    options: [
      { id: "a", text: "L must be {a^n | n is odd}" },
      { id: "b", text: "L must be {a^n | n is even}" },
      { id: "c", text: "L must be {a^n | n ≥ 0}" },
      { id: "d", text: "Either L must be {a^n | n is odd} or L must be {a^n | n is even}" },
    ],
    correctOptionId: "d",
    explanation:
      "Over a one-symbol alphabet, a 2-state minimal automaton can only be tracking the parity of the a-count — one state for 'even so far', one for 'odd so far', toggling on every a. Whichever state is marked accepting determines whether L is the odd-length language or the even-length language, so it must be one of those two (it can't be 'all strings', which needs just 1 state).",
  },
  {
    id: "toc-g10",
    text: "The smallest FA which accepts the language {x | length of x is divisible by 3} has",
    topic: "Finite Automata — GATE Questions",
    options: [
      { id: "a", text: "2 states" },
      { id: "b", text: "3 states" },
      { id: "c", text: "4 states" },
      { id: "d", text: "5 states" },
    ],
    correctOptionId: "b",
    explanation:
      "Only the length of x matters here, not which symbols appear, so the machine just needs to track length mod 3 — one state each for remainder 0 (accepting), 1, and 2 — advancing to the next state on any symbol. Three states are necessary and sufficient.",
  },
  {
    id: "toc-g12",
    text: "The following finite state machine accepts all those binary strings in which the number of 1's and 0's are, respectively,",
    topic: "Finite Automata — GATE Questions",
    options: [
      { id: "a", text: "divisible by 3 and 2" },
      { id: "b", text: "odd and even" },
      { id: "c", text: "even and odd" },
      { id: "d", text: "divisible by 2 and 3" },
    ],
    correctOptionId: "a",
    explanation:
      "This is a product of a mod-3 counter (for the 1's) and a mod-2 counter (for the 0's), giving 3 x 2 = 6 states — one for every (count of 1's mod 3, count of 0's mod 2) pair. The start/accept state is the (0, 0) pair, so the machine accepts exactly the strings whose number of 1's is divisible by 3 and whose number of 0's is divisible by 2.",
  },
  {
    id: "toc-g13",
    text: "Consider the machine M. The language recognized by M is:",
    topic: "Finite Automata — GATE Questions",
    options: [
      { id: "a", text: "{w ε{a, b}* | every a in w is followed by exactly two b's}" },
      { id: "b", text: "{w ε{a, b}* | every a in w is followed by at least two b's}" },
      { id: "c", text: "{w ε{a, b}* | w contains the substring 'abb'}" },
      { id: "d", text: "{w ε{a, b}* | w does not contain 'aa' as a substring}" },
    ],
    correctOptionId: "a",
    explanation:
      "The accepting start state (with a self-loop on b) moves to a 'need one b' state on reading a, then to a 'need a second b' state, then back to the accepting state — completing exactly two b's after every a. Reading an a too early, before both required b's arrive, sends the machine into a non-accepting trap it can never leave, which is what enforces 'exactly two' rather than 'at least two'.",
  },
  {
    id: "toc-g14",
    text: "A minimum state deterministic FA accepting the language L = {w | w ε {0, 1}*} where number of 0's and 1's in w are divisible by 3 and 5, respectively, has",
    topic: "Finite Automata — GATE Questions",
    options: [
      { id: "a", text: "15 states" },
      { id: "b", text: "11 states" },
      { id: "c", text: "10 states" },
      { id: "d", text: "9 states" },
    ],
    correctOptionId: "a",
    explanation:
      "This is a product of a mod-3 counter (for the 0's) and a mod-5 counter (for the 1's): 3 x 5 = 15 states, one for every combination of the two remainders.",
  },
  {
    id: "toc-g16",
    text: "The given DFA accepts the set of all strings over {0, 1} that",
    topic: "Finite Automata — GATE Questions",
    options: [
      { id: "a", text: "begin either with 0 or 1." },
      { id: "b", text: "end with 0" },
      { id: "c", text: "end with 00." },
      { id: "d", text: "contain the substring 00." },
    ],
    correctOptionId: "c",
    explanation:
      "This is the standard 3-state 'ends with 00' construction: the start state has a self-loop on 1 (a leading run of 1's is irrelevant), advances on each 0 seen, and the accepting state has a self-loop on 0 (further trailing 0's still end in 00). Any 1 seen after the first 0 breaks the pattern and sends the machine back to the start.",
  },
  {
    id: "toc-g17",
    text: "Let w be any string of length n in {0, 1}*. Let L be the set of all substrings of w. What is the minimum number of states in a non-deterministic FA that accepts L?",
    topic: "Finite Automata — GATE Questions",
    options: [
      { id: "a", text: "n – 1" },
      { id: "b", text: "n" },
      { id: "c", text: "n + 1" },
      { id: "d", text: "2^(n-1)" },
    ],
    correctOptionId: "c",
    explanation:
      "Build a chain of n+1 states following the characters of w, and mark every state along the chain as accepting. Non-determinism lets the machine 'guess' which position to start reading from, so any contiguous run of w's characters — i.e. any substring — traces a path to an accepting state, using only n+1 states total.",
  },
  {
    id: "toc-g18",
    text: "Definition of a language L with alphabet {a} is given as following {a^(nk) | k > 0 and n is a positive integer constant}. What is the minimum number of states needed in a DFA to recognize L?",
    topic: "Finite Automata — GATE Questions",
    options: [
      { id: "a", text: "k + 1" },
      { id: "b", text: "n + 1" },
      { id: "c", text: "2^(n+1)" },
      { id: "d", text: "2^(k+1)" },
    ],
    correctOptionId: "b",
    explanation:
      "Since n is a fixed constant, the machine tracks the a-count modulo n using n states — but it also needs to tell 'seen 0 a's' apart from 'seen exactly n a's', since only positive multiples of n should be accepted (k > 0 excludes the empty string). That extra distinction needs one more state beyond the n remainder-states, for n + 1 total.",
  },
  {
    id: "toc-g20",
    text: "The __________ of a set of states, P, of an NFA is defined as the set of states reachable from any state in P following e-transitions.",
    topic: "Finite Automata — GATE Questions",
    options: [
      { id: "a", text: "e-closure" },
      { id: "b", text: "e-pack" },
      { id: "c", text: "Q in the tuple" },
      { id: "d", text: "None of the mentioned" },
    ],
    correctOptionId: "a",
    explanation:
      "This is the definition of the epsilon-closure (e-closure) of a set of states — the states reachable purely by following ε-transitions, with no input symbol consumed.",
  },
  {
    id: "toc-g21",
    text: "The transition function of NFA Is",
    topic: "Finite Automata — GATE Questions",
    options: [
      { id: "a", text: "Q×Σ→Q" },
      { id: "b", text: "Q×Σ→2^n" },
      { id: "c", text: "Q×Σ→Q^n" },
      { id: "d", text: "Q×Σ→2^Q" },
    ],
    correctOptionId: "d",
    explanation:
      "An NFA's transition function maps a (state, symbol) pair to a set of possible next states — an element of the power set of Q — so δ: Q x Σ → 2^Q.",
  },

  {
    id: "toc-u1-q1",
    text: "The transitional function of a DFA is",
    topic: "Finite Automata",
    options: [
      { id: "a", text: "Q \u00d7 \u03a3 \u2192 Q" },
      { id: "b", text: "Q \u00d7 \u03a3 \u2192 2Q" },
      { id: "c", text: "Q \u00d7 \u03a3 \u2192 2n" },
      { id: "d", text: "Q \u00d7 \u03a3 \u2192 Qn" }
    ],
    correctOptionId: "a",
    explanation: "Answer provided by question bank."
  },
  {
    id: "toc-u1-q2",
    text: "Which of the following is an application of Finite Automaton?",
    topic: "Finite Automata",
    options: [
      { id: "a", text: "Compiler Design" },
      { id: "b", text: "Grammar Parsers" },
      { id: "c", text: "Text Search" },
      { id: "d", text: "All of the mentioned" }
    ],
    correctOptionId: "d",
    explanation: "Answer provided by question bank."
  },
  {
    id: "toc-u1-q3",
    text: "Predict the number of transitions required to automate the following language using only 3 states: L = {w | w ends with 00}",
    topic: "Finite Automata",
    options: [
      { id: "a", text: "3" },
      { id: "b", text: "2" },
      { id: "c", text: "4" },
      { id: "d", text: "6" }
    ],
    correctOptionId: "a",
    explanation: "Answer provided by question bank."
  },
  {
    id: "toc-u1-q4",
    text: "If L is a regular language, Lc and Lr both will be:",
    topic: "Finite Automata",
    options: [
      { id: "a", text: "Accepted by NFA" },
      { id: "b", text: "Rejected by NFA" },
      { id: "c", text: "One of them will be accepted" },
      { id: "d", text: "Cannot be said" }
    ],
    correctOptionId: "a",
    explanation: "Answer provided by question bank."
  },
  {
    id: "toc-u1-q5",
    text: "In NFA, this very state is like dead-end non final state:",
    topic: "Finite Automata",
    options: [
      { id: "a", text: "ACCEPT" },
      { id: "b", text: "REJECT" },
      { id: "c", text: "DISNTICT" },
      { id: "d", text: "START" }
    ],
    correctOptionId: "b",
    explanation: "Answer provided by question bank."
  },
  {
    id: "toc-u1-q6",
    text: "Which among the following can be an example of application of finite state machine (FSM)?",
    topic: "Finite Automata",
    options: [
      { id: "a", text: "Communication Link" },
      { id: "b", text: "Adder" },
      { id: "c", text: "Stack" },
      { id: "d", text: "None of the mentioned" }
    ],
    correctOptionId: "a",
    explanation: "Answer provided by question bank."
  },
  {
    id: "toc-u1-q7",
    text: "The number of tuples in an extended Non-Deterministic Finite Automaton:",
    topic: "Finite Automata",
    options: [
      { id: "a", text: "5" },
      { id: "b", text: "6" },
      { id: "c", text: "7" },
      { id: "d", text: "4" }
    ],
    correctOptionId: "a",
    explanation: "Answer provided by question bank."
  },
  {
    id: "toc-u1-q8",
    text: "A finite automaton recognizes",
    topic: "Finite Automata",
    options: [
      { id: "a", text: "Any language" },
      { id: "b", text: "Context sensitive language" },
      { id: "c", text: "Context-free language" },
      { id: "d", text: "Regular language" }
    ],
    correctOptionId: "d",
    explanation: "Answer provided by question bank."
  },
  {
    id: "toc-u1-q9",
    text: "NFA, in its name has \u2019non-deterministic\u2019 because of :",
    topic: "Finite Automata",
    options: [
      { id: "a", text: "The result is undetermined" },
      { id: "b", text: "The choice of path is non-deterministic" },
      { id: "c", text: "The state to be transited next is non-deterministic" },
      { id: "d", text: "All of the mentioned" }
    ],
    correctOptionId: "b",
    explanation: "Answer provided by question bank."
  },
  {
    id: "toc-u1-q10",
    text: "The given DFA accepts the set of all strings over {0, 1} that",
    diagramUrl: "/diagrams/toc_u1/toc_q10_0.png",
    topic: "Finite Automata",
    options: [
      { id: "a", text: "begin either with 0 or 1" },
      { id: "b", text: "end with 00" },
      { id: "c", text: "contain the substring 00" },
      { id: "d", text: "end with 0" }
    ],
    correctOptionId: "b",
    explanation: "Answer provided by question bank."
  },
  {
    id: "toc-u1-q11",
    text: "A language is regular if and only if",
    topic: "Finite Automata",
    options: [
      { id: "a", text: "accepted by DFA" },
      { id: "b", text: "accepted by PDA" },
      { id: "c", text: "accepted by LBA" },
      { id: "d", text: "accepted by Turing machine" }
    ],
    correctOptionId: "a",
    explanation: "Answer provided by question bank."
  },
  {
    id: "toc-u1-q12",
    text: "In the context of a finite automaton, the extended transition function is denoted by:",
    topic: "Finite Automata",
    options: [
      { id: "a", text: "\u03b4q, a)" },
      { id: "b", text: "\u03b4^(q, a)q, w)" },
      { id: "c", text: "q0" },
      { id: "d", text: "Q'" }
    ],
    correctOptionId: "b",
    explanation: "Answer provided by question bank."
  },
  {
    id: "toc-u1-q14",
    text: "How is the extended transition function \u03b4 defined recursively in terms of the standard transition function \u03b4 for a non-empty string w = xa (where x is a string and a is a symbol)?",
    topic: "Finite Automata",
    options: [
      { id: "a", text: "\u03b4^(q, a)q, w) = \u03b4q, a)" },
      { id: "b", text: "\u03b4^(q, a)q, w) = \u03b4^(q, a)\u03b4q, a), x)" },
      { id: "c", text: "\u03b4^(q, a)q, w) = \u03b4\u03b4^(q, a)q, x), a)" },
      { id: "d", text: "\u03b4^(q, a)q, w) = \u03b4q, w)" }
    ],
    correctOptionId: "c",
    explanation: "Answer provided by question bank."
  },
  {
    id: "toc-u1-q15",
    text: "The maximum number of states of a DFA converted from an NFA with n states is",
    topic: "Finite Automata",
    options: [
      { id: "a", text: "n" },
      { id: "b", text: "n2" },
      { id: "c", text: "2n" },
      { id: "d", text: "n*n*n" }
    ],
    correctOptionId: "c",
    explanation: "Answer provided by question bank."
  },
  {
    id: "toc-u1-q16",
    text: "\u03b5 + RR* = ?",
    topic: "Finite Automata",
    options: [
      { id: "a", text: "R" },
      { id: "b", text: "R+" },
      { id: "c", text: "R*" },
      { id: "d", text: "\u03b5" }
    ],
    correctOptionId: "c",
    explanation: "Answer provided by question bank."
  },
  {
    id: "toc-u1-q17",
    text: "Which regular expression best describes the language accepted by the following non- deterministic automation?",
    diagramUrl: "/diagrams/toc_u1/toc_q17_1.png",
    topic: "Finite Automata",
    options: [
      { id: "a", text: "(q, a)abb)*" },
      { id: "b", text: "(q, a)a + b)*" },
      { id: "c", text: "(q, a)a + b)* a(q, a)a + b)b" },
      { id: "d", text: "(q, a)a + b)*a(q, a)a + b)*b(q, a)a + b)*" }
    ],
    correctOptionId: "c",
    explanation: "Answer provided by question bank."
  },
  {
    id: "toc-u1-q18",
    text: "Which type of string is accepted by the following finite automata?",
    topic: "Finite Automata",
    options: [
      { id: "a", text: "All string" },
      { id: "b", text: "Null string" },
      { id: "c", text: "String with only a\u2019s" },
      { id: "d", text: "String with only b\u2019s" }
    ],
    correctOptionId: "b",
    explanation: "Answer provided by question bank."
  },
  {
    id: "toc-u1-q19",
    text: "The string 1101 does not belong to the set represented by",
    topic: "Finite Automata",
    options: [
      { id: "a", text: "(q, a)00 + (q, a)11)*01)*" },
      { id: "b", text: "(q, a)10)*(q, a)01)*(q, a)00 + 11)*" },
      { id: "c", text: "1(q, a)0 + 1)*101" },
      { id: "d", text: "110*(q, a)0 + 1)" }
    ],
    correctOptionId: "b",
    explanation: "Answer provided by question bank."
  },
  {
    id: "toc-u1-q20",
    text: "The transition function of an NFA is",
    topic: "Finite Automata",
    options: [
      { id: "a", text: "Q \u00d7 \u03a3 \u2192 Q" },
      { id: "b", text: "Q \u00d7 \u03a3 \u2192 2Q" },
      { id: "c", text: "Q \u00d7 \u03a3 \u2192 2n" },
      { id: "d", text: "Q \u00d7 \u03a3 \u2192 Qn" }
    ],
    correctOptionId: "b",
    explanation: "Answer provided by question bank."
  },
  {
    id: "toc-u1-q21",
    text: "Which of the following languages is not regular?",
    topic: "Finite Automata",
    options: [
      { id: "a", text: "{anbn\u2223n\u22650}" },
      { id: "b", text: "{anbm\u2223n\u22650 and m\u22650}" },
      { id: "c", text: "{w\u2223w contains an even number of 0\u2019s}" },
      { id: "d", text: "{w\u2223w is a string of 0\u2019s and 1\u2019s}" }
    ],
    correctOptionId: "a",
    explanation: "Answer provided by question bank."
  },
  {
    id: "toc-u1-q22",
    text: "Which of the following regular expression indicates set of strings consisting of any number of a\u2019s (may be empty string also) followed by any number of b\u2019s(may be empty string also)",
    topic: "Finite Automata",
    options: [
      { id: "a", text: "**a*b" },
      { id: "b", text: "a*a*b*" },
      { id: "c", text: "a*b*" },
      { id: "d", text: "ab*" }
    ],
    correctOptionId: "c",
    explanation: "Answer provided by question bank."
  },
  {
    id: "toc-u1-q23",
    text: "The Pumping Lemma for Regular Languages is used to prove that a language is not regular",
    topic: "Finite Automata",
    options: [
      { id: "a", text: "False" },
      { id: "b", text: "True" },
      { id: "c", text: "Partially false" },
      { id: "d", text: "May be true or false" }
    ],
    correctOptionId: "b",
    explanation: "Answer provided by question bank."
  },
  {
    id: "toc-u1-q24",
    text: "The basic limitations of a finite state machine is",
    topic: "Finite Automata",
    options: [
      { id: "a", text: "It cannot remember arbitrarily large amount of information" },
      { id: "b", text: "It cannot remember state transitions" },
      { id: "c", text: "It cannot remember grammar for a language" },
      { id: "d", text: "It cannot remember language generated from a grammar" }
    ],
    correctOptionId: "a",
    explanation: "Answer provided by question bank."
  },
  {
    id: "toc-u1-q25",
    text: "Which is true for a dead state?",
    topic: "Finite Automata",
    options: [
      { id: "a", text: "It cannot be reached anytime" },
      { id: "b", text: "There is no necessity of the state" },
      { id: "c", text: "If control enters, there is no way to come out from the state" },
      { id: "d", text: "If control enters, FA is dead" }
    ],
    correctOptionId: "c",
    explanation: "Answer provided by question bank."
  },
  {
    id: "toc-u1-q26",
    text: "The language accepted by the given FA is",
    diagramUrl: "/diagrams/toc_u1/toc_q26_3.jpeg",
    topic: "Finite Automata",
    options: [
      { id: "a", text: "(q, a)ab)*" },
      { id: "b", text: "bb*a" },
      { id: "c", text: "b(q, a)ba)*a" },
      { id: "d", text: "Null" }
    ],
    correctOptionId: "d",
    explanation: "Answer provided by question bank."
  },
  {
    id: "toc-u1-q27",
    text: "The language of all words with at least 2 a\u2019s can be described by the regular expression",
    topic: "Finite Automata",
    options: [
      { id: "a", text: "(q, a)ab)*a" },
      { id: "b", text: "(q, a)a + b)*ab*(q, a)a + b)*" },
      { id: "c", text: "b*ab*(q, a)a + b)*" },
      { id: "d", text: "(q, a)a+b)*a(q, a)a+b)*a(q, a)a+b)*" }
    ],
    correctOptionId: "d",
    explanation: "Answer provided by question bank."
  },
  {
    id: "toc-u1-q28",
    text: "The set of all strings of {0, 1} having exactly two 0\u2019s is",
    topic: "Finite Automata",
    options: [
      { id: "a", text: "1*01*01*" },
      { id: "b", text: "{0 + 1)*1" },
      { id: "c", text: "{11 + 0}*" },
      { id: "d", text: "{00 + 11}*" }
    ],
    correctOptionId: "a",
    explanation: "Answer provided by question bank."
  },
  {
    id: "toc-u1-q29",
    text: "After applying the State Elimination Method to a finite automaton, what is the result?",
    topic: "Finite Automata",
    options: [
      { id: "a", text: "A minimized deterministic finite automaton" },
      { id: "b", text: "A regular expression" },
      { id: "c", text: "A regular grammar" },
      { id: "d", text: "A non-deterministic pushdown automaton" }
    ],
    correctOptionId: "b",
    explanation: "Answer provided by question bank."
  },
  {
    id: "toc-u1-q30",
    text: "Which of the strings do not belong to the regular expression (ba + baa)*aaba",
    topic: "Finite Automata",
    options: [
      { id: "a", text: "baaaba" },
      { id: "b", text: "babaabaaaba" },
      { id: "c", text: "babababa" },
      { id: "d", text: "baaaaba" }
    ],
    correctOptionId: "c",
    explanation: "Answer provided by question bank."
  },
  {
    id: "toc-u1-q31",
    text: "Which of the languages is accepted by the following FA?",
    diagramUrl: "/diagrams/toc_u1/toc_q31_4.png",
    topic: "Finite Automata",
    options: [
      { id: "a", text: "b(q, a)a + bba*)*a* b" },
      { id: "b", text: "a(q, a)a + bba*)*b*" },
      { id: "c", text: "a(q, a)a + bb*a*)*b*d" },
      { id: "d", text: "a*(q, a)ba*b)*" }
    ],
    correctOptionId: "d",
    explanation: "Answer provided by question bank."
  },
  {
    id: "toc-u1-q32",
    text: "The pumping lemma for regular language is used to prove that",
    topic: "Finite Automata",
    options: [
      { id: "a", text: "Certain sets are regular" },
      { id: "b", text: "Certain sets are not regular" },
      { id: "c", text: "Certain regular grammar produce RE" },
      { id: "d", text: "Certain regular grammar does not produce RE" }
    ],
    correctOptionId: "b",
    explanation: "Answer provided by question bank."
  },
  {
    id: "toc-u1-q33",
    text: "Regular languages are closed under",
    topic: "Finite Automata",
    options: [
      { id: "a", text: "Union" },
      { id: "b", text: "Concatenation" },
      { id: "c", text: "Kleene closure" },
      { id: "d", text: "All of the above" }
    ],
    correctOptionId: "d",
    explanation: "Answer provided by question bank."
  },
  {
    id: "toc-u1-q34",
    text: "Consider the strings u = abbaba, v = bab, and w = aabb. Which of the following statement is true for the given transitional system?",
    diagramUrl: "/diagrams/toc_u1/toc_q34_5.png",
    topic: "Finite Automata",
    options: [
      { id: "a", text: "The automaton accepts u and v but not w." },
      { id: "b", text: "The automaton accepts each of u, v, and w." },
      { id: "c", text: "The automaton rejects each of u, v, and w." },
      { id: "d", text: "The automaton accepts u but rejects v and w." }
    ],
    correctOptionId: "d",
    explanation: "Answer provided by question bank."
  },
  {
    id: "toc-u1-q35",
    text: "What is the primary purpose of the State Elimination Method?",
    topic: "Finite Automata",
    options: [
      { id: "a", text: "To minimize the number of states in a finite automaton" },
      { id: "b", text: "To convert a finite automaton into a regular expression" },
      { id: "c", text: "To convert a regular expression into a finite automaton" },
      { id: "d", text: "To remove unreachable states from the finite automaton" }
    ],
    correctOptionId: "b",
    explanation: "Answer provided by question bank."
  },
  {
    id: "toc-u1-q36",
    text: "Which of the following is true for the epsilon closure of a state q in a Non-deterministic Finite Automaton (NFA)?",
    topic: "Finite Automata",
    options: [
      { id: "a", text: "It includes only the state q itself." },
      { id: "b", text: "It includes all states that can be reached from q via epsilon transitions." },
      { id: "c", text: "It includes all states that can be reached from q via any input symbol." },
      { id: "d", text: "It includes no states." }
    ],
    correctOptionId: "b",
    explanation: "Answer provided by question bank."
  },
  {
    id: "toc-u1-q38",
    text: "Consider the transitional system  Which of the states are to be marked as starting state and final state, respectively, so as to turn the above system into a DFA that accepts all strings having odd number of zeros and even number of 1\u2019s?",
    diagramUrl: "/diagrams/toc_u1/toc_q38_6.png",
    topic: "Finite Automata",
    options: [
      { id: "a", text: "q0, q2" },
      { id: "b", text: "q0, q1" },
      { id: "c", text: "q1, q2" },
      { id: "d", text: "q2, q3" }
    ],
    correctOptionId: "c",
    explanation: "Answer provided by question bank."
  },
  {
    id: "toc-u1-q39",
    text: "Consider the following DFA in which S0 is the start state and S1 and S4 are the final states.  Which one is true?",
    diagramUrl: "/diagrams/toc_u1/toc_q39_7.png",
    topic: "Finite Automata",
    options: [
      { id: "a", text: "All strings of x and y." },
      { id: "b", text: "All strings of x and y which have either an even number of x and even number of y or an oddnumber of x and odd number of y." },
      { id: "c", text: "All strings of x and y which have an equal number of x and y." },
      { id: "d", text: "All strings of x and y which have either an even number of x and odd number of y or an oddnumber of x and even number of y." }
    ],
    correctOptionId: "d",
    explanation: "Answer provided by question bank."
  },
  {
    id: "toc-u1-q40",
    text: "Let N be an NFA with n states and let M be the minimized DFA with m states recognizing the same language. Which of the following is NECESSARILY true?",
    topic: "Finite Automata",
    options: [
      { id: "a", text: "m \u2264 2n" },
      { id: "b", text: "n \u2264 m" },
      { id: "c", text: "M has one accept state" },
      { id: "d", text: "m = 2n" }
    ],
    correctOptionId: "a",
    explanation: "Answer provided by question bank."
  },
  {
    id: "toc-u1-q41",
    text: "The smallest FA which accepts the language {x | length of x is divisible by 3} has",
    topic: "Finite Automata",
    options: [
      { id: "a", text: "2 states" },
      { id: "b", text: "3 states" },
      { id: "c", text: "4 states" },
      { id: "d", text: "5 states" }
    ],
    correctOptionId: "b",
    explanation: "Answer provided by question bank."
  },
  {
    id: "toc-u1-q42",
    text: "Which of the following is true about the extended transition function \u03b4^(q0, \u03b5) for any state q0, where \u03b5 is the empty string?",
    topic: "Finite Automata",
    options: [
      { id: "a", text: "\u03b4^(q, a)q0, \u03b5) = qF" },
      { id: "b", text: "\u03b4^(q, a)q0, \u03b5) = q0" },
      { id: "c", text: "\u03b4^(q, a)q0, \u03b5) = F" },
      { id: "d", text: "\u03b4^(q, a)q0, \u03b5) = undefined" }
    ],
    correctOptionId: "b",
    explanation: "Answer provided by question bank."
  },
  {
    id: "toc-u1-q43",
    text: "There exists a language L. We define a string w such that w\u2208L and w=xyz and |w| >=n for some constant integer n. What can be the maximum length of the substring xy i.e. |xy|<=?",
    topic: "Finite Automata",
    options: [
      { id: "a", text: "n" },
      { id: "b", text: "|y|" },
      { id: "c", text: "|x|" },
      { id: "d", text: "None of the mentioned" }
    ],
    correctOptionId: "a",
    explanation: "Answer provided by question bank."
  },
  {
    id: "toc-u1-q44",
    text: "What does the regular expression a*ba* represent?",
    topic: "Finite Automata",
    options: [
      { id: "a", text: "Strings with exactly one 'b' and any number of 'a's" },
      { id: "b", text: "Strings that start and end with 'a'" },
      { id: "c", text: "Strings with no 'b'" },
      { id: "d", text: "Strings with one or more 'b's" }
    ],
    correctOptionId: "a",
    explanation: "Answer provided by question bank."
  },
  {
    id: "toc-u1-q45",
    text: "The regular expression \u03b5 represents which of the following?",
    topic: "Finite Automata",
    options: [
      { id: "a", text: "The set containing only the empty string" },
      { id: "b", text: "The empty set" },
      { id: "c", text: "The set containing all strings" },
      { id: "d", text: "A string of length 1" }
    ],
    correctOptionId: "a",
    explanation: "Answer provided by question bank."
  },
  {
    id: "toc-u1-q46",
    text: "The following finite state machine accepts all those binary strings in which the number of  1\u2019s and 0\u2019s are, respectively,",
    diagramUrl: "/diagrams/toc_u1/toc_q46_8.png",
    topic: "Finite Automata",
    options: [
      { id: "a", text: "divisible by 3 and 2" },
      { id: "b", text: "odd and even" },
      { id: "c", text: "even and odd" },
      { id: "d", text: "divisible by 2 and 3" }
    ],
    correctOptionId: "a",
    explanation: "Answer provided by question bank."
  },
  {
    id: "toc-u1-q47",
    text: "When converting an NFA to a regular expression using the State Elimination Method, which of the following states are typically preserved?",
    topic: "Finite Automata",
    options: [
      { id: "a", text: "Intermediate states" },
      { id: "b", text: "Start and final states" },
      { id: "c", text: "Only the state with the fewest transitions" },
      { id: "d", text: "All states except the start state" }
    ],
    correctOptionId: "b",
    explanation: "Answer provided by question bank."
  },
  {
    id: "toc-u1-q48",
    text: "Answer in  accordance  to  the  third  and  last  statement  in  pumping  lemma:  For all _______ xykz \u20ac L.",
    topic: "Finite Automata",
    options: [
      { id: "a", text: "k<0" },
      { id: "b", text: "k>0" },
      { id: "c", text: "k\u22650" },
      { id: "d", text: "k\u22640" }
    ],
    correctOptionId: "c",
    explanation: "Answer provided by question bank."
  },
  {
    id: "toc-u1-q49",
    text: "Which of the following regular expressions describe the language over {0, 1} consisting of strings that contain exactly two 1\u2019s?",
    topic: "Finite Automata",
    options: [
      { id: "a", text: "(q, a)0 + 1)*11(q, a)0 + 1)*" },
      { id: "b", text: "0*110*" },
      { id: "c", text: "0*10*10*" },
      { id: "d", text: "(q, a)0 + 1)*1(q, a)0 + 1)*1(q, a)0 + 1)*" }
    ],
    correctOptionId: "c",
    explanation: "Answer provided by question bank."
  },
  {
    id: "toc-u1-q50",
    text: "Which of the following regular expressions denotes the set of all strings over the alphabet {0, 1} that begin and end with 1?",
    topic: "Finite Automata",
    options: [
      { id: "a", text: "1(q, a)0+1)*1" },
      { id: "b", text: "(q, a)1(q, a)0+1))*1" },
      { id: "c", text: "1(q, a)0+1)1*" },
      { id: "d", text: "1(q, a)1*0)*0" }
    ],
    correctOptionId: "a",
    explanation: "Answer provided by question bank."
  },
  {
    id: "toc-u1-q51",
    text: "A Language for which no DFA exist is a________",
    topic: "Finite Automata",
    options: [
      { id: "a", text: "Regular Language" },
      { id: "b", text: "Non-Regular Language" },
      { id: "c", text: "May be Regular" },
      { id: "d", text: "Cannot be said" }
    ],
    correctOptionId: "a",
    explanation: "Answer provided by question bank."
  },
  {
    id: "toc-u1-q52",
    text: "Which of the following best describes a regular expression?",
    topic: "Finite Automata",
    options: [
      { id: "a", text: "A formal description of a language" },
      { id: "b", text: "A graphical representation of a finite automaton" },
      { id: "c", text: "A method to calculate the shortest path in a graph" },
      { id: "d", text: "A sequence of symbols and operators to define a set of strings" }
    ],
    correctOptionId: "d",
    explanation: "Answer provided by question bank."
  },
  {
    id: "toc-u1-q53",
    text: "Find the false statement if S = (a, b)",
    topic: "Finite Automata",
    options: [
      { id: "a", text: "L = {anbm, m, n \u2265 1} is regular" },
      { id: "b", text: "L = {X, where na(q, a)X) > nb(q, a)X)} is not regular" },
      { id: "c", text: "L = {anbn, n \u2265 1} is regular" },
      { id: "d", text: "L = {X, where na(q, a)X) = nb(q, a)X)} is not regular" }
    ],
    correctOptionId: "c",
    explanation: "Answer provided by question bank."
  },
  {
    id: "toc-u1-q54",
    text: "The string 1101 does not belong to the set represented by",
    topic: "Finite Automata",
    options: [
      { id: "a", text: "110*(q, a)0 + 1)" },
      { id: "b", text: "1(q, a)0 + 1)*101" },
      { id: "c", text: "(q, a)10)*(q, a)01)*(q, a)00 + 11)*" },
      { id: "d", text: "(q, a)00 + (q, a)11)*01)*" }
    ],
    correctOptionId: "c",
    explanation: "Answer provided by question bank."
  },
  {
    id: "toc-u1-q55",
    text: "What is the purpose of the + symbol in regular expressions?",
    topic: "Finite Automata",
    options: [
      { id: "a", text: "It matches zero or more occurrences of the preceding element." },
      { id: "b", text: "It matches exactly one occurrence of the preceding element." },
      { id: "c", text: "It matches one or more occurrences of the preceding element." },
      { id: "d", text: "It matches any single character." }
    ],
    correctOptionId: "c",
    explanation: "Answer provided by question bank."
  },
  {
    id: "toc-u1-q56",
    text: "Which one of the following languages over the alphabet {0, 1} is described by the  regular expression:  (0 + 1)*0(0 + l)*0(0 + 1)* ?",
    topic: "Finite Automata",
    options: [
      { id: "a", text: "The set of all strings containing the substring 00." },
      { id: "b", text: "The set of all strings containing at most two 0\u2019s." },
      { id: "c", text: "The set of all strings containing at least two 0\u2019s." },
      { id: "d", text: "The set of all strings that begin and end with either 0 or 1" }
    ],
    correctOptionId: "c",
    explanation: "Answer provided by question bank."
  },
  {
    id: "toc-u1-q57",
    text: "What does the regular expression a*b represent?",
    topic: "Finite Automata",
    options: [
      { id: "a", text: "Zero or more occurrences of b followed by one a" },
      { id: "b", text: "Exactly one occurrence of a followed by zero or more occurrences of b" },
      { id: "c", text: "Zero or more occurrences of a followed by one b" },
      { id: "d", text: "Exactly one occurrence of b followed by zero or more occurrences of a" }
    ],
    correctOptionId: "c",
    explanation: "Answer provided by question bank."
  },
  {
    id: "toc-u1-q58",
    text: "In  a  Non-deterministic  Finite  Automaton  (NFA)  with  \u03b5-transitions,  which  of  the following statements is true?",
    topic: "Finite Automata",
    options: [
      { id: "a", text: "An \u03b5-transition allows the automaton to change states without consuming any inputsymbol." },
      { id: "b", text: "\u03b5-transitions are not allowed in Deterministic Finite Automata (q, a)DFA)." },
      { id: "c", text: "\u03b5-transitions can only be used to transition between states that have the same symbol intheir transition function." },
      { id: "d", text: "An NFA with \u03b5-transitions can always be converted to an equivalent DFA without \u03b5-transitions." }
    ],
    correctOptionId: "a",
    explanation: "Answer provided by question bank."
  },
  {
    id: "toc-u1-q60",
    text: "\u03b4^(q,ya) is equivalent to:",
    topic: "Finite Automata",
    options: [
      { id: "a", text: "\u03b4(q, a)q,y),a)" },
      { id: "b", text: "\u03b4q,ya)" },
      { id: "c", text: "\u03b4\u03b4^(q, a)q,y),a)" },
      { id: "d", text: "independent from \u03b4 notation" }
    ],
    correctOptionId: "c",
    explanation: "Answer provided by question bank."
  },
  {
    id: "toc-u1-q61",
    text: "\u0278 in minimal finite automata need _____________ no. of final states.",
    topic: "Finite Automata",
    options: [
      { id: "a", text: "1" },
      { id: "b", text: "2" },
      { id: "c", text: "3" },
      { id: "d", text: "None" }
    ],
    correctOptionId: "d",
    explanation: "Answer provided by question bank."
  },
  {
    id: "toc-u1-q62",
    text: "Subset Construction method used for:",
    topic: "Finite Automata",
    options: [
      { id: "a", text: "Conversion of NFA to DFA" },
      { id: "b", text: "DFA minimization" },
      { id: "c", text: "Eliminating Null references" },
      { id: "d", text: "\u03b5-NFA to NFA" }
    ],
    correctOptionId: "a",
    explanation: "Answer provided by question bank."
  },
  {
    id: "toc-u1-q63",
    text: "An NFA\u2019s transition function returns",
    diagramUrl: "/diagrams/toc_u1/toc_q63_13.jpeg",
    topic: "Finite Automata",
    options: [
      { id: "a", text: "A state" },
      { id: "b", text: "A Boolean value" },
      { id: "c", text: "An edge" },
      { id: "d", text: "A set of states" }
    ],
    correctOptionId: "d",
    explanation: "Answer provided by question bank."
  },
  {
    id: "toc-u1-q64",
    text: "If we select a string w such that w\u2208L, and w=xyz. Which of the following portions cannot be an empty string?",
    topic: "Finite Automata",
    options: [
      { id: "a", text: "x" },
      { id: "b", text: "y" },
      { id: "c", text: "z" },
      { id: "d", text: "x and z" }
    ],
    correctOptionId: "b",
    explanation: "Answer provided by question bank."
  },
];
